### PR TITLE
Attempt to unbreak Cypress envs

### PR DESCRIPTION
**Pull request by HaraldNordgren**

### CODE REVIEW

**Comment by fenske** [comment]
Hi @HaraldNordgren . This is a boilerplate's repo. Did you want to push it to your coding test repo instead?

**Comment by Harald-Proposales-DevSkills** [comment]
Hi Anton! 👋🏻

It wasn't a mistake. I couldn't get Cypress tests to find my code at all without changing this 🤗

**Comment by HaraldNordgren** [comment]
Hi Anton! 👋🏻

It wasn't a mistake. I couldn't get Cypress tests to find my code at all without changing this 🤗

**Comment by fenske** [comment]
Oh, I see what happened.

Let me walk you through it: https://www.loom.com/share/ee9b1f9ef2e24d418f30b2297e29ec3e

**Comment by fenske** [comment]
I'll close this PR in the meantime.

**Pull request closed without merging**
